[package]
name = "unzip_7z"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
progress_bar = { path = "../progress_bar" }
rayon = "1.10"
sevenz-rust = { version = "0.6.0", features = ["aes256"] }
